services:
  pygeoapi:
    build:
      context: ./
      secrets:
        - GH_TOKEN
    ports:
      - "5000:80"
    volumes:
      - data_volume:/pygeoapi/data
  downloader:
    build:
      context: ./docker/downloader/
      secrets:
        - GH_TOKEN
    volumes:
      - data_volume:/data
    depends_on:
      - pygeoapi

volumes:
  data_volume:
    name: pygeoapi-datavolume

secrets:
  GH_TOKEN:
    file: ./GH_TOKEN
