version: "3"
services:
  pygeoapi:
    build: ./
    ports: 
      - "5000:80"
    volumes:
      - data_volume:/pygeoapi/data
  downloader:
    build: ./docker/downloader/
    volumes:
      - data_volume:/data
volumes:
  data_volume:
    name: pygeoapi-datavolume