FROM python

RUN apt-get update -y && apt-get install git
RUN apt-get install wget -y
RUN wget -O "/data/bild.png" "https://d1q6f0aelx0por.cloudfront.net/product-logos/library-python-logo.png"

CMD "sleep" "1d"